# Especifica la versión exacta de OpenAPI.
openapi: 3.1.9

# 1. Información básica de tu API
info:
  title: API de Conversaciones
  description: Maneja la creación, gestión y membresía de todas las conversaciones (grupos y chats directos).
  version: 1.0.0
  contact:
    name: Equipo de Desarrollo
    email: dev@ejemplo.com

# 2. Servidores
servers:
  - url: /api/v1/conversacion
    description: Servidor de desarrollo

# 3. Tags
# Define los tags usados en 'paths' para agrupar endpoints en la UI de Swagger.
tags:
  - name: Conversacion
    description: Operaciones sobre el recurso principal de conversación (grupos y DMs).
  - name: Miembro
    description: Operaciones para gestionar los miembros de una conversación.

# 4. Componentes Reutilizables
components:
  # --- Esquemas (DTOs) ---
  schemas:
    # Schema estándar para respuestas de error
    ErrorResponse:
      type: object
      properties:
        tipo:
          type: string
          description: Un URI de referencia al tipo de problema.
          example: "https://ejemplo.com/errores/validacion"
        titulo:
          type: string
          description: Un resumen legible del problema.
          example: "Error de validación"
        estado:
          type: integer
          description: El código de estado HTTP.
          example: 400
        detalle:
          type: string
          description: Una explicación detallada del error.
          example: "El campo 'nombre' no puede estar vacío."

    # DTO que representa a un usuario (datos de Usuarios.API)
    UsuarioResumenResponse:
      type: object
      description: Representación resumida de un usuario.
      properties:
        id:
          type: string
          description: El ID del usuario (de Auth0/Usuarios.API).
          example: "auth0|507f1f77bcf86cd799439011"
        nombre:
          type: string
          example: "Usuario Falso 1"
        avatarUrl:
          nullable: true
          format: uri
          description: "URL del avatar del usuario."
          example: "https://example.com/avatars/user1.png"

    # DTO para la respuesta de una conversación detallada
    ConversacionResponse:
      type: object
      description: Representación detallada de una conversación (grupo o DM).
      required:
        - id
        - tipo
        - miembros
      properties:
        id:
          type: string
          format: uuid
        tipo:
          type: string
          enum: ["directo", "grupo"]
          description: "El tipo de conversación."
        nombre:
          type: string
          nullable: true
          description: "El nombre (solo para 'grupo')."
          example: "Proyecto Final"
        avatarUrl:
          type: string
          format: uri
          nullable: true
        miembros:
          type: array
          items:
            $ref: "#/components/schemas/UsuarioResumenResponse"

    # DTO para crear un GRUPO
    CrearGrupoRequest:
      type: object
      required:
        - nombre
      properties:
        nombre:
          type: string
          description: "Nombre del nuevo grupo."
          example: "Grupo de Programación IV"
        miembrosIniciales:
          type: array
          description: "Lista de IDs de usuarios para agregar al grupo."
          items:
            type: string
          example: ["auth0|507f1f77bcf86cd799439011"]

    # DTO para iniciar un CHAT DIRECTO
    IniciarChatDirectoRequest:
      type: object
      required:
        - otroUsuarioId
      properties:
        otroUsuarioId:
          type: string
          description: "ID del otro usuario para el chat 1-a-1."
          example: "auth0|507f1f77bcf86cd799439011"

    # DTO para actualizar un GRUPO
    ActualizarGrupoRequest:
      type: object
      properties:
        nombre:
          type: string
          description: "El nuevo nombre del grupo."
          example: "Grupo TUP 2025"
        avatarUrl:
          type: string
          format: uri
          nullable: true
          description: "La nueva URL del avatar del grupo."

    # DTO para agregar un miembro
    AgregarMiembroRequest:
      type: object
      required:
        - usuarioId
      properties:
        usuarioId:
          type: string
          description: "ID del usuario a agregar (formato Auth0)"
          example: "auth0|507f1f77bcf86cd799439011"

  # --- Esquemas de Seguridad ---
  securitySchemes:
    auth0Jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Token JWT provisto por Auth0."

# 5. Seguridad Global
security:
  - auth0Jwt: []

# 6. Paths (Endpoints)
# Todos los paths son relativos a la URL del servidor: /api/v1/conversacion
paths:
  # --- Path: / ---
  /:
    get:
      tags:
        - Conversacion
      summary: "Listar las conversaciones (grupos y DMs) del usuario."
      operationId: ListarConversacionesUsuario
      responses:
        "200":
          description: "Lista de conversaciones a las que pertenece el usuario."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ConversacionResponse"
        "401":
          description: "No autorizado."

  # --- Path: /grupo ---
  /grupo:
    post:
      tags:
        - Conversacion
      summary: "Crear un nuevo grupo."
      description: "Crea una conversación de tipo 'grupo'."
      operationId: CrearGrupo
      requestBody:
        description: Datos para el nuevo grupo.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrearGrupoRequest"
      responses:
        "201":
          description: "Grupo creado exitosamente."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversacionResponse"
        "400":
          $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "No autorizado."

  # --- Path: /directo ---
  /directo:
    post:
      tags:
        - Conversacion
      summary: "Iniciar o recuperar un chat directo (1-a-1)."
      description: "Busca una conversación 'directo' existente con el otro usuario. Si no existe, la crea."
      operationId: IniciarChatDirecto
      requestBody:
        description: El otro usuario con el que se quiere chatear.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IniciarChatDirectoRequest"
      responses:
        "200":
          description: "Conversación directa recuperada."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversacionResponse"
        "201":
          description: "Conversación directa creada."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversacionResponse"
        "401":
          description: "No autorizado."
        "404":
          description: "El 'otroUsuarioId' no fue encontrado."

  # --- Path: /{conversacionId} ---
  /{conversacionId}:
    parameters:
      - name: conversacionId
        in: path
        required: true
        description: El ID de la conversación.
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Conversacion
      summary: "Obtener detalles de una conversación (grupo o DM)."
      operationId: ObtenerConversacionPorId
      responses:
        "200":
          description: "Detalles de la conversación."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversacionResponse"
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado (no eres miembro)."
        "404":
          description: "Conversación no encontrada."

    put:
      tags:
        - Conversacion
      summary: "Actualizar una conversación (ej. cambiar nombre de grupo)."
      description: "Solo aplicable a conversaciones tipo 'grupo'."
      operationId: ActualizarConversacion
      requestBody:
        description: Campos a actualizar en la conversación.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActualizarGrupoRequest"
      responses:
        "200":
          description: "Conversación actualizada."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversacionResponse"
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado (no eres admin o no es un grupo)."
        "404":
          description: "Conversación no encontrada."

    delete:
      tags:
        - Conversacion
      summary: "Eliminar o abandonar una conversación."
      operationId: EliminarConversacion
      responses:
        "204":
          description: "Conversación eliminada/abandonada (Sin contenido)."
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado."
        "404":
          description: "Conversación no encontrada."

  # --- Path: /{conversacionId}/miembros ---
  /{conversacionId}/miembros:
    parameters:
      - name: conversacionId
        in: path
        required: true
        description: El ID de la conversación.
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Miembro
      summary: "Listar los miembros de una conversación."
      operationId: ListarMiembros
      responses:
        "200":
          description: "Lista de miembros."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioResumenResponse"
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado (no eres miembro)."
        "404":
          description: "Conversación no encontrada."

    post:
      tags:
        - Miembro
      summary: "Agregar un miembro a un grupo."
      description: "Solo aplicable a conversaciones tipo 'grupo'."
      operationId: AgregarMiembro
      requestBody:
        description: El usuario a agregar.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AgregarMiembroRequest"
      responses:
        "200":
          description: "Miembro agregado exitosamente."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Miembro agregado exitosamente"
        "400":
          description: "Error al agregar miembro."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado (no eres admin o no es un grupo)."
        "404":
          description: "Conversación o usuario no encontrado."

  # --- Path: /{conversacionId}/miembros/{usuarioId} ---
  /{conversacionId}/miembros/{usuarioId}:
    parameters:
      - name: conversacionId
        in: path
        required: true
        description: El ID de la conversación.
        schema:
          type: string
          format: uuid
      - name: usuarioId
        in: path
        required: true
        description: El ID del usuario a quitar (formato Auth0).
        schema:
          type: string
        example: "auth0|507f1f77bcf86cd799439011"

    delete:
      tags:
        - Miembro
      summary: "Quitar un miembro de una conversación."
      description: "En un grupo, saca al usuario. En un chat directo, es similar a 'abandonar' el chat."
      operationId: QuitarMiembro
      responses:
        "204":
          description: "Miembro quitado (Sin contenido)."
        "401":
          description: "No autorizado."
        "403":
          description: "Acceso denegado."
        "404":
          description: "Conversación o miembro no encontrado."
